# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hyperparameters.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HyperparametersPage(object):
    def setupUi(self, HyperparametersPage):
        HyperparametersPage.setObjectName("HyperparametersPage")
        HyperparametersPage.resize(464, 489)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Logo.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        HyperparametersPage.setWindowIcon(icon)
        HyperparametersPage.setToolTip("")
        HyperparametersPage.setWhatsThis("")
        HyperparametersPage.setAccessibleName("")
        self.centralwidget = QtWidgets.QWidget(HyperparametersPage)
        self.centralwidget.setObjectName("centralwidget")
        self.mainModelGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mainModelGroupBox.setGeometry(QtCore.QRect(10, 190, 441, 221))
        self.mainModelGroupBox.setObjectName("mainModelGroupBox")
        self.LearningRateSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.LearningRateSpinBox.setGeometry(QtCore.QRect(250, 30, 62, 22))
        self.LearningRateSpinBox.setDecimals(4)
        self.LearningRateSpinBox.setMaximum(9999.0)
        self.LearningRateSpinBox.setSingleStep(0.0001)
        self.LearningRateSpinBox.setProperty("value", 0.001)
        self.LearningRateSpinBox.setObjectName("LearningRateSpinBox")
        self.L1RegularizationSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.L1RegularizationSpinBox.setGeometry(QtCore.QRect(250, 60, 62, 22))
        self.L1RegularizationSpinBox.setDecimals(2)
        self.L1RegularizationSpinBox.setMaximum(9999.0)
        self.L1RegularizationSpinBox.setSingleStep(0.01)
        self.L1RegularizationSpinBox.setProperty("value", 200.0)
        self.L1RegularizationSpinBox.setObjectName("L1RegularizationSpinBox")
        self.ValBatchSizeSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.ValBatchSizeSpinBox.setGeometry(QtCore.QRect(250, 90, 62, 22))
        self.ValBatchSizeSpinBox.setDecimals(0)
        self.ValBatchSizeSpinBox.setMaximum(9999.0)
        self.ValBatchSizeSpinBox.setProperty("value", 0.0)
        self.ValBatchSizeSpinBox.setObjectName("ValBatchSizeSpinBox")
        self.TrainBatchSizeSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.TrainBatchSizeSpinBox.setGeometry(QtCore.QRect(250, 120, 62, 22))
        self.TrainBatchSizeSpinBox.setDecimals(0)
        self.TrainBatchSizeSpinBox.setMaximum(9999.0)
        self.TrainBatchSizeSpinBox.setProperty("value", 0.0)
        self.TrainBatchSizeSpinBox.setObjectName("TrainBatchSizeSpinBox")
        self.epochsSpinBox = QtWidgets.QDoubleSpinBox(self.mainModelGroupBox)
        self.epochsSpinBox.setGeometry(QtCore.QRect(250, 150, 62, 22))
        self.epochsSpinBox.setDecimals(0)
        self.epochsSpinBox.setMaximum(9999.0)
        self.epochsSpinBox.setProperty("value", 12.0)
        self.epochsSpinBox.setObjectName("epochsSpinBox")
        self.epochsLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.epochsLabel.setGeometry(QtCore.QRect(140, 150, 71, 16))
        self.epochsLabel.setObjectName("epochsLabel")
        self.learningRateLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.learningRateLabel.setGeometry(QtCore.QRect(140, 30, 71, 16))
        self.learningRateLabel.setObjectName("learningRateLabel")
        self.epochsLabel_2 = QtWidgets.QLabel(self.mainModelGroupBox)
        self.epochsLabel_2.setGeometry(QtCore.QRect(140, 120, 91, 16))
        self.epochsLabel_2.setObjectName("epochsLabel_2")
        self.ValBatchLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.ValBatchLabel.setGeometry(QtCore.QRect(140, 90, 101, 16))
        self.ValBatchLabel.setObjectName("ValBatchLabel")
        self.L1RegularizationLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.L1RegularizationLabel.setGeometry(QtCore.QRect(140, 60, 91, 16))
        self.L1RegularizationLabel.setObjectName("L1RegularizationLabel")
        self.ClassTypeCombo = QtWidgets.QComboBox(self.mainModelGroupBox)
        self.ClassTypeCombo.setGeometry(QtCore.QRect(250, 180, 91, 22))
        self.ClassTypeCombo.setObjectName("ClassTypeCombo")
        self.ClassTypeCombo.addItem("")
        self.ClassTypeCombo.addItem("")
        self.ClassLabel = QtWidgets.QLabel(self.mainModelGroupBox)
        self.ClassLabel.setGeometry(QtCore.QRect(140, 180, 71, 16))
        self.ClassLabel.setObjectName("ClassLabel")
        self.trainModelButton = QtWidgets.QPushButton(self.centralwidget)
        self.trainModelButton.setGeometry(QtCore.QRect(310, 420, 130, 25))
        self.trainModelButton.setObjectName("trainModelButton")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(50, 420, 75, 23))
        self.BackButton.setObjectName("BackButton")
        self.LogoName = QtWidgets.QLabel(self.centralwidget)
        self.LogoName.setGeometry(QtCore.QRect(90, 10, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(28)
        font.setItalic(True)
        self.LogoName.setFont(font)
        self.LogoName.setObjectName("LogoName")
        self.LogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogoLabel.setGeometry(QtCore.QRect(120, 0, 221, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoLabel.sizePolicy().hasHeightForWidth())
        self.LogoLabel.setSizePolicy(sizePolicy)
        self.LogoLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LogoLabel.setObjectName("LogoLabel")
        HyperparametersPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HyperparametersPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 21))
        self.menubar.setObjectName("menubar")
        HyperparametersPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HyperparametersPage)
        self.statusbar.setObjectName("statusbar")
        HyperparametersPage.setStatusBar(self.statusbar)

        self.retranslateUi(HyperparametersPage)
        QtCore.QMetaObject.connectSlotsByName(HyperparametersPage)

    def retranslateUi(self, HyperparametersPage):
        _translate = QtCore.QCoreApplication.translate
        HyperparametersPage.setWindowTitle(_translate("HyperparametersPage", "Hyperparameters"))
        self.mainModelGroupBox.setTitle(_translate("HyperparametersPage", "Model"))
        self.epochsLabel.setText(_translate("HyperparametersPage", "Epochs"))
        self.learningRateLabel.setText(_translate("HyperparametersPage", "Learning rate"))
        self.epochsLabel_2.setText(_translate("HyperparametersPage", "Training Batch size"))
        self.ValBatchLabel.setText(_translate("HyperparametersPage", "Validation Batch size"))
        self.L1RegularizationLabel.setText(_translate("HyperparametersPage", "L1 Regularization"))
        self.ClassTypeCombo.setCurrentText(_translate("HyperparametersPage", "Two_Classes"))
        self.ClassTypeCombo.setItemText(0, _translate("HyperparametersPage", "Two_Classes"))
        self.ClassTypeCombo.setItemText(1, _translate("HyperparametersPage", "Three_Classes"))
        self.ClassLabel.setText(_translate("HyperparametersPage", "Class Type"))
        self.trainModelButton.setText(_translate("HyperparametersPage", "Train"))
        self.BackButton.setText(_translate("HyperparametersPage", "Back"))
        self.LogoName.setText(_translate("HyperparametersPage", "<html><head/><body><p><span style=\" font-size:24pt; color:#00009e;\">Anti Fraud Damage Detector</span></p></body></html>"))
        self.LogoLabel.setText(_translate("HyperparametersPage", "<html><head/><body><p><img src=\"Logo.png\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HyperparametersPage = QtWidgets.QMainWindow()
    ui = Ui_HyperparametersPage()
    ui.setupUi(HyperparametersPage)
    HyperparametersPage.show()
    sys.exit(app.exec_())
