# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Hyperparameters.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HyperparametersWindow(object):
    def setupUi(self, HyperparametersWindow):
        HyperparametersWindow.setObjectName("HyperparametersWindow")
        HyperparametersWindow.resize(366, 517)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('Logo.png'), QtGui.QIcon.Selected, QtGui.QIcon.On)
        HyperparametersWindow.setWindowIcon(icon)
        HyperparametersWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(HyperparametersWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(60, 10, 231, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Logo.sizePolicy().hasHeightForWidth())
        self.Logo.setSizePolicy(sizePolicy)
        self.Logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Logo.setObjectName("Logo")
        self.LogoName = QtWidgets.QLabel(self.centralwidget)
        self.LogoName.setGeometry(QtCore.QRect(30, 10, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Brush Script MT")
        font.setPointSize(28)
        font.setItalic(True)
        self.LogoName.setFont(font)
        self.LogoName.setObjectName("LogoName")
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton.setGeometry(QtCore.QRect(30, 220, 56, 17))
        self.BrowseButton.setObjectName("BrowseButton")
        self.BrowseEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.BrowseEdit.setGeometry(QtCore.QRect(90, 210, 241, 31))
        self.BrowseEdit.setTabStopWidth(80)
        self.BrowseEdit.setObjectName("BrowseEdit")
        self.LearningRateInput = QtWidgets.QTextEdit(self.centralwidget)
        self.LearningRateInput.setGeometry(QtCore.QRect(10, 310, 41, 31))
        self.LearningRateInput.setObjectName("LearningRateInput")
        self.BatchSizeInput = QtWidgets.QTextEdit(self.centralwidget)
        self.BatchSizeInput.setGeometry(QtCore.QRect(10, 350, 41, 31))
        self.BatchSizeInput.setObjectName("BatchSizeInput")
        self.EpochesInput = QtWidgets.QTextEdit(self.centralwidget)
        self.EpochesInput.setGeometry(QtCore.QRect(10, 390, 41, 31))
        self.EpochesInput.setObjectName("EpochesInput")
        self.SoftMargineInput = QtWidgets.QTextEdit(self.centralwidget)
        self.SoftMargineInput.setGeometry(QtCore.QRect(180, 310, 41, 31))
        self.SoftMargineInput.setObjectName("SoftMargineInput")
        self.KernalDegreeInput = QtWidgets.QTextEdit(self.centralwidget)
        self.KernalDegreeInput.setGeometry(QtCore.QRect(180, 350, 41, 31))
        self.KernalDegreeInput.setObjectName("KernalDegreeInput")
        self.TrainingLabel = QtWidgets.QLabel(self.centralwidget)
        self.TrainingLabel.setGeometry(QtCore.QRect(40, 260, 41, 16))
        self.TrainingLabel.setObjectName("TrainingLabel")
        self.ValidationLabel = QtWidgets.QLabel(self.centralwidget)
        self.ValidationLabel.setGeometry(QtCore.QRect(260, 260, 61, 20))
        self.ValidationLabel.setObjectName("ValidationLabel")
        self.LearningRateLabel = QtWidgets.QLabel(self.centralwidget)
        self.LearningRateLabel.setGeometry(QtCore.QRect(60, 310, 71, 31))
        self.LearningRateLabel.setObjectName("LearningRateLabel")
        self.BatchSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.BatchSizeLabel.setGeometry(QtCore.QRect(60, 350, 51, 31))
        self.BatchSizeLabel.setObjectName("BatchSizeLabel")
        self.EpochesLabel = QtWidgets.QLabel(self.centralwidget)
        self.EpochesLabel.setGeometry(QtCore.QRect(60, 390, 41, 31))
        self.EpochesLabel.setObjectName("EpochesLabel")
        self.SoftMargineLabel = QtWidgets.QLabel(self.centralwidget)
        self.SoftMargineLabel.setGeometry(QtCore.QRect(230, 310, 111, 31))
        self.SoftMargineLabel.setObjectName("SoftMargineLabel")
        self.KernalDegreeLabel = QtWidgets.QLabel(self.centralwidget)
        self.KernalDegreeLabel.setGeometry(QtCore.QRect(230, 350, 71, 31))
        self.KernalDegreeLabel.setObjectName("KernalDegreeLabel")
        self.ScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.ScrollBar.setGeometry(QtCore.QRect(90, 260, 160, 16))
        self.ScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.ScrollBar.setObjectName("ScrollBar")
        self.TeachButton = QtWidgets.QPushButton(self.centralwidget)
        self.TeachButton.setGeometry(QtCore.QRect(260, 440, 91, 31))
        self.TeachButton.setObjectName("TeachButton")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 440, 61, 31))
        self.BackButton.setObjectName("BackButton")
        self.TrainPrecentage = QtWidgets.QLabel(self.centralwidget)
        self.TrainPrecentage.setGeometry(QtCore.QRect(50, 280, 31, 16))
        self.TrainPrecentage.setObjectName("TrainPrecentage")
        self.ValPrecentage = QtWidgets.QLabel(self.centralwidget)
        self.ValPrecentage.setGeometry(QtCore.QRect(270, 280, 31, 16))
        self.ValPrecentage.setObjectName("ValPrecentage")
        HyperparametersWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HyperparametersWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 366, 21))
        self.menubar.setObjectName("menubar")
        HyperparametersWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HyperparametersWindow)
        self.statusbar.setObjectName("statusbar")
        HyperparametersWindow.setStatusBar(self.statusbar)

        self.retranslateUi(HyperparametersWindow)
        QtCore.QMetaObject.connectSlotsByName(HyperparametersWindow)

    def retranslateUi(self, HyperparametersWindow):
        _translate = QtCore.QCoreApplication.translate
        HyperparametersWindow.setWindowTitle(_translate("HyperparametersWindow", "Hyperparameters"))
        self.Logo.setText(_translate("HyperparametersWindow", "<html><head/><body><p><img src=\"Logo.png\"/></p></body></html>"))
        self.LogoName.setText(_translate("HyperparametersWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#00009e;\">Anti Fraud Damage Detector</span></p></body></html>"))
        self.BrowseButton.setText(_translate("HyperparametersWindow", "Browse"))
        self.TrainingLabel.setText(_translate("HyperparametersWindow", "Training"))
        self.ValidationLabel.setText(_translate("HyperparametersWindow", "Validation"))
        self.LearningRateLabel.setText(_translate("HyperparametersWindow", "Leaning rate"))
        self.BatchSizeLabel.setText(_translate("HyperparametersWindow", "Batch size"))
        self.EpochesLabel.setText(_translate("HyperparametersWindow", "Epoches"))
        self.SoftMargineLabel.setText(_translate("HyperparametersWindow", "Soft margine constant"))
        self.KernalDegreeLabel.setText(_translate("HyperparametersWindow", "Kernal degree"))
        self.TeachButton.setText(_translate("HyperparametersWindow", "Teach & Validate"))
        self.BackButton.setText(_translate("HyperparametersWindow", "Back"))
        self.TrainPrecentage.setText(_translate("HyperparametersWindow", "99%"))
        self.ValPrecentage.setText(_translate("HyperparametersWindow", "99%"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainApplicationWindow1 = QtWidgets.QMainWindow()
    ui = Ui_HyperparametersWindow()
    ui.setupUi(MainApplicationWindow1)
    MainApplicationWindow1.show()
    sys.exit(app.exec_())
